version: "3.8"
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Soundify
      MYSQL_USER: Soundify
      MYSQL_PASSWORD: Soundify
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    # Alternative healthcheck that uses a simpler command
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-uroot",
          "-proot",
          "-e",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./backend/backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Soundify
      SPRING_DATASOURCE_USERNAME: Soundify
      SPRING_DATASOURCE_PASSWORD: Soundify

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
