version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soundify
      MYSQL_USER: sounduser
      MYSQL_PASSWORD: soundpass
    ports:
      - '3307:3306'

  backend:
    build:
      context: ./backend/backend
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soundify
      SPRING_DATASOURCE_USERNAME: sounduser
      SPRING_DATASOURCE_PASSWORD: soundpass

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - '3000:80'
