services:
  db:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Soundify
      MYSQL_USER: Soundify
      MYSQL_PASSWORD: Soundify
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./backend/backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Soundify
      SPRING_DATASOURCE_USERNAME: Soundify
      SPRING_DATASOURCE_PASSWORD: Soundify
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data:
