FROM mariadb:latest

# SQL-Init-Skript kopieren
COPY init.sql /docker-entrypoint-initdb.d/

# MariaDB-Port freigeben
EXPOSE 3306

# Healthcheck anpassen (Host auf 'localhost' bleibt okay hier, weil der Healthcheck im Container läuft)
HEALTHCHECK --interval=5s --timeout=5s --retries=3 \
    CMD mysqladmin ping -h localhost -u root -proot || exit 1
