name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.yaml up -d --build

      - name: Wait for backend to be ready
        run: |
          for i in {1..30}; do
            if curl --fail http://localhost:8080/; then
              echo "Backend is up!"
              exit 0
            else
              echo "Waiting for backend..."
              sleep 2
            fi
          done
          echo "Backend did not start in time"
          exit 1

      - name: Tear down containers
        if: always()
        run: docker-compose down
