name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: example
          MARIADB_DATABASE: soundify
          MARIADB_USER: sounduser
          MARIADB_PASSWORD: soundpass
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: docker-compose up -d --build

    - name: Wait for Backend to be healthy
      run: |
        for i in {1..10}; do
          status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/actuator/health)
          if [ "$status" -eq 200 ]; then
            echo "Backend is healthy"
            exit 0
          fi
          echo "Waiting for backend..."
          sleep 5
        done
        exit 1

    - name: Run E2E CRUD Tests
      run: |
        # Beispiel: Prüfe ob Hello-Endpoint antwortet
        curl -f http://localhost:8080/api/hello
        # Hier könnt ihr eure echten CRUD Tests einbauen, z.B. mit curl oder Postman/newman

    - name: Tear down Docker Compose
      if: always()
      run: docker-compose down
