name: Simple DB Test

on:
  push:
    branches:
      - main

jobs:
  test-db:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Check MariaDB health
      run: |
        for i in {1..10}; do
          if docker ps | grep healthy; then
            echo "MariaDB is healthy"
            exit 0
          fi
          echo "Waiting for MariaDB to be healthy..."
          sleep 5
        done
        echo "MariaDB did not become healthy in time"
        docker logs $(docker ps -q)
        exit 1

    - name: Shut down Docker Compose
      run: docker-compose down
