name: Hello World Compose Test

on:
  push:
    branches:
      - main

jobs:
  hello-world-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Start Docker Compose
        run: docker-compose up

      - name: Done
        run: echo "Hello world container should have printed a message."

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
