name: Docker Compose Deployment Test

on:
  push:
    branches:
      - main

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Start Docker Compose in detached mode
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start..."
          sleep 30  # Give services time to start

      - name: Check if containers are running
        run: docker-compose ps

      - name: Check database service
        run: |
          docker-compose exec -T db mysqladmin ping -h localhost -uroot -proot || echo "Database not ready yet"

      - name: Test backend service
        run: |
          curl -s http://localhost:8080 || echo "Backend service not responding"

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down -v
